name: Markdown linter runner

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.md"
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.md"

jobs:
  lint:
    name: mdl runner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Install dependencies
      run: pnpm install --lockfile=false
    - name: Run Markdownlint
      run: pnpm md:lint
